notifications:
  email: false

language: php
sudo: false

php:
  - 7.3
  - 7.2

env:
  global:
    - PLUGIN=IMAPUserAuth
    - KANBOARD_REPO=https://github.com/kanboard/kanboard.git
  matrix:
    - DB=sqlite

matrix:
  fast_finish: true

install:
  - git clone --depth 1 $KANBOARD_REPO
  - ln -s $TRAVIS_BUILD_DIR kanboard/plugins/$PLUGIN

before_script:
  - cd kanboard
  - composer install
  - composer require elvanto/picodb
  - ls -la plugins/

script:
  - ./vendor/bin/phpunit -c tests/units.$DB.xml plugins/$PLUGIN/Test/
